packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.51.23
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  eslint: ^9.9.0
  prettier: ^3.3.3
  superjson: ^2.2.1
  typescript: ^5.5.4
  zod: ^3.23.8

catalogs:
  dates:
    date-fns: ^3.6.0
    luxon: ^3.5.0
    "@types/luxon": ^3.4.2
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
  supabase:
    "@supabase/supabase-js": ^2.45.3
    "@supabase/ssr": ^0.5.1
    "@supabase/auth-helpers-react": ^0.5.0
  tailwind:
    tailwindcss: ^3.4.10
    tailwindcss-animate: ^1.0.7
