packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.51.9
  "@trpc/client": ^11.0.0-rc.466
  "@trpc/react-query": ^11.0.0-rc.466
  "@trpc/server": ^11.0.0-rc.466
  eslint: ^9.7.0
  prettier: ^3.3.3
  superjson: ^2.2.1
  typescript: ^5.5.4
  zod: ^3.23.8

catalogs:
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
  supabase:
    "@supabase/supabase-js": ^2.45.0
    "@supabase/ssr": ^0.4.0
    "@supabase/auth-helpers-react": ^0.5.0
  tailwind:
    tailwindcss: ^3.4.7
    tailwindcss-animate: ^1.0.7
