packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.59.19
  "@trpc/client": ^11.0.0-rc.608
  "@trpc/react-query": ^11.0.0-rc.608
  "@trpc/server": ^11.0.0-rc.608
  "@types/node": ^20.16.11
  eslint: ^9.14.0
  prettier: ^3.3.3
  superjson: ^2.2.1
  typescript: ^5.6.3
  zod: ^3.23.8

catalogs:
  dates:
    date-fns: ^4.1.0
    "@date-fns/tz": ^1.1.2
    luxon: ^3.5.0
    "@types/luxon": ^3.4.2
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    "@types/react": ^18.3.12
    "@types/react-dom": ^18.3.1
  supabase:
    "@supabase/supabase-js": ^2.46.1
    "@supabase/ssr": ^0.5.1
    "@supabase/auth-helpers-react": ^0.5.0
  tailwind:
    tailwindcss: ^3.4.14
    tailwindcss-animate: ^1.0.7
